//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// CODEGEN: The binding 'NetTcpBinding_IOnlineSupportService' from namespace 'http://tempuri.org/' was ignored.  There is no SoapTransportImporter that understands the transport 'http://schemas.microsoft.com/soap/tcp'.
// CODEGEN: The binding 'NetNamedPipeBinding_IOnlineSupportService' from namespace 'http://tempuri.org/' was ignored.  There is no SoapTransportImporter that understands the transport 'http://schemas.microsoft.com/soap/named-pipe'.
// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.3603.
// 
namespace MobileClient.OSS {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    // CODEGEN: The optional WSDL extension element 'EndpointReference' from namespace 'http://www.w3.org/2005/08/addressing' was not handled.
    // CODEGEN: The binding 'NetTcpBinding_IOnlineSupportService' from namespace 'http://tempuri.org/' was ignored.  There is no SoapTransportImporter that understands the transport 'http://schemas.microsoft.com/soap/tcp'.
    // CODEGEN: The binding 'NetNamedPipeBinding_IOnlineSupportService' from namespace 'http://tempuri.org/' was ignored.  There is no SoapTransportImporter that understands the transport 'http://schemas.microsoft.com/soap/named-pipe'.
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSHttpBinding_IOnlineSupportService", Namespace="http://tempuri.org/")]
    public partial class OnlineSupportService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public OnlineSupportService() {
            this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
            this.Url = "http://localhost:8180/oss";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IOnlineSupportService/ClientStart", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ClientStart([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userName) {
            object[] results = this.Invoke("ClientStart", new object[] {
                        userName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginClientStart(string userName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ClientStart", new object[] {
                        userName}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndClientStart(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IOnlineSupportService/ClientEnd", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ClientEnd(string userID, out bool ClientEndResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool ClientEndResultSpecified) {
            object[] results = this.Invoke("ClientEnd", new object[] {
                        userID});
            ClientEndResult = ((bool)(results[0]));
            ClientEndResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginClientEnd(string userID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ClientEnd", new object[] {
                        userID}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndClientEnd(System.IAsyncResult asyncResult, out bool ClientEndResult, out bool ClientEndResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            ClientEndResult = ((bool)(results[0]));
            ClientEndResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IOnlineSupportService/OperatorStart", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OperatorStart([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string userName) {
            object[] results = this.Invoke("OperatorStart", new object[] {
                        userName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginOperatorStart(string userName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("OperatorStart", new object[] {
                        userName}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndOperatorStart(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IOnlineSupportService/OperatorEnd", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void OperatorEnd(string userID, out bool OperatorEndResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool OperatorEndResultSpecified) {
            object[] results = this.Invoke("OperatorEnd", new object[] {
                        userID});
            OperatorEndResult = ((bool)(results[0]));
            OperatorEndResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginOperatorEnd(string userID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("OperatorEnd", new object[] {
                        userID}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndOperatorEnd(System.IAsyncResult asyncResult, out bool OperatorEndResult, out bool OperatorEndResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            OperatorEndResult = ((bool)(results[0]));
            OperatorEndResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IOnlineSupportService/GetOperators", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/OnlineSupportServiceLibrary.Entities")]
        public OperatorData[] GetOperators() {
            object[] results = this.Invoke("GetOperators", new object[0]);
            return ((OperatorData[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetOperators(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetOperators", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public OperatorData[] EndGetOperators(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((OperatorData[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IOnlineSupportService/GetClients", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/OnlineSupportServiceLibrary.Entities")]
        public ClientData[] GetClients() {
            object[] results = this.Invoke("GetClients", new object[0]);
            return ((ClientData[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetClients(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetClients", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public ClientData[] EndGetClients(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ClientData[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IOnlineSupportService/ClientSendMessage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ClientSendMessage(string userID, string operatorID, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string message, out bool ClientSendMessageResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool ClientSendMessageResultSpecified) {
            object[] results = this.Invoke("ClientSendMessage", new object[] {
                        userID,
                        operatorID,
                        message});
            ClientSendMessageResult = ((bool)(results[0]));
            ClientSendMessageResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginClientSendMessage(string userID, string operatorID, string message, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ClientSendMessage", new object[] {
                        userID,
                        operatorID,
                        message}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndClientSendMessage(System.IAsyncResult asyncResult, out bool ClientSendMessageResult, out bool ClientSendMessageResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            ClientSendMessageResult = ((bool)(results[0]));
            ClientSendMessageResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IOnlineSupportService/OperatorSendMessage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void OperatorSendMessage(string operatorID, string userID, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string message, out bool OperatorSendMessageResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool OperatorSendMessageResultSpecified) {
            object[] results = this.Invoke("OperatorSendMessage", new object[] {
                        operatorID,
                        userID,
                        message});
            OperatorSendMessageResult = ((bool)(results[0]));
            OperatorSendMessageResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginOperatorSendMessage(string operatorID, string userID, string message, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("OperatorSendMessage", new object[] {
                        operatorID,
                        userID,
                        message}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndOperatorSendMessage(System.IAsyncResult asyncResult, out bool OperatorSendMessageResult, out bool OperatorSendMessageResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            OperatorSendMessageResult = ((bool)(results[0]));
            OperatorSendMessageResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IOnlineSupportService/ClientGetMessages", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/OnlineSupportServiceLibrary.Entities")]
        public ChatData[] ClientGetMessages(string userID, System.DateTime lastOperationTime, [System.Xml.Serialization.XmlIgnoreAttribute()] bool lastOperationTimeSpecified) {
            object[] results = this.Invoke("ClientGetMessages", new object[] {
                        userID,
                        lastOperationTime,
                        lastOperationTimeSpecified});
            return ((ChatData[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginClientGetMessages(string userID, System.DateTime lastOperationTime, bool lastOperationTimeSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ClientGetMessages", new object[] {
                        userID,
                        lastOperationTime,
                        lastOperationTimeSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public ChatData[] EndClientGetMessages(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ChatData[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IOnlineSupportService/OperatorGetMessages", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/OnlineSupportServiceLibrary.Entities")]
        public ChatData[] OperatorGetMessages(string OperatorID, System.DateTime lastOperationTime, [System.Xml.Serialization.XmlIgnoreAttribute()] bool lastOperationTimeSpecified) {
            object[] results = this.Invoke("OperatorGetMessages", new object[] {
                        OperatorID,
                        lastOperationTime,
                        lastOperationTimeSpecified});
            return ((ChatData[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginOperatorGetMessages(string OperatorID, System.DateTime lastOperationTime, bool lastOperationTimeSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("OperatorGetMessages", new object[] {
                        OperatorID,
                        lastOperationTime,
                        lastOperationTimeSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public ChatData[] EndOperatorGetMessages(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ChatData[])(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/OnlineSupportServiceLibrary.Entities")]
    public partial class OperatorData {
        
        private System.DateTime lastOperationTimeField;
        
        private bool lastOperationTimeFieldSpecified;
        
        private System.DateTime onlineTimeField;
        
        private bool onlineTimeFieldSpecified;
        
        private string operatorIDField;
        
        private string operatorNameField;
        
        /// <remarks/>
        public System.DateTime LastOperationTime {
            get {
                return this.lastOperationTimeField;
            }
            set {
                this.lastOperationTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastOperationTimeSpecified {
            get {
                return this.lastOperationTimeFieldSpecified;
            }
            set {
                this.lastOperationTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime OnlineTime {
            get {
                return this.onlineTimeField;
            }
            set {
                this.onlineTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OnlineTimeSpecified {
            get {
                return this.onlineTimeFieldSpecified;
            }
            set {
                this.onlineTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string OperatorID {
            get {
                return this.operatorIDField;
            }
            set {
                this.operatorIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OperatorName {
            get {
                return this.operatorNameField;
            }
            set {
                this.operatorNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/OnlineSupportServiceLibrary.Entities")]
    public partial class ChatData {
        
        private System.DateTime sendingTimeField;
        
        private string recieverNameField;
        
        private string senderNameField;
        
        private string messageField;
        
        /// <remarks/>
        public System.DateTime SendingTime {
            get {
                return this.sendingTimeField;
            }
            set {
                this.sendingTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RecieverName {
            get {
                return this.recieverNameField;
            }
            set {
                this.recieverNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SenderName {
            get {
                return this.senderNameField;
            }
            set {
                this.senderNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/OnlineSupportServiceLibrary.Entities")]
    public partial class ClientData {
        
        private string clientIDField;
        
        private string clientNameField;
        
        private System.DateTime lastOperationTimeField;
        
        private bool lastOperationTimeFieldSpecified;
        
        private System.DateTime onlineTimeField;
        
        private bool onlineTimeFieldSpecified;
        
        /// <remarks/>
        public string ClientID {
            get {
                return this.clientIDField;
            }
            set {
                this.clientIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ClientName {
            get {
                return this.clientNameField;
            }
            set {
                this.clientNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastOperationTime {
            get {
                return this.lastOperationTimeField;
            }
            set {
                this.lastOperationTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastOperationTimeSpecified {
            get {
                return this.lastOperationTimeFieldSpecified;
            }
            set {
                this.lastOperationTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime OnlineTime {
            get {
                return this.onlineTimeField;
            }
            set {
                this.onlineTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OnlineTimeSpecified {
            get {
                return this.onlineTimeFieldSpecified;
            }
            set {
                this.onlineTimeFieldSpecified = value;
            }
        }
    }
}
